import { SpinBox, Button, CheckBox, Slider, LineEdit, ScrollView, ListView,
    HorizontalBox, VerticalBox, GridBox, StandardButton, StandardTableView } from "std-widgets.slint";

import { ViewToDoItem } from "viewtodoitem.slint";

export component AppWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    min-width: 800px;
    min-height: 600px;

    callback item-checked(ViewToDoItem);
    callback item-unchecked(ViewToDoItem);

    in property <[ViewToDoItem]> todo-items;

    VerticalBox {
        ListView {
            for item in root.todo-items: HorizontalLayout {
                spacing: 10px;

                item-action := CheckBox {
                    in property <ViewToDoItem> todo: item;
                    checked: item.checked;
                    horizontal-stretch: 0;

                    toggled => {
                        item.checked = self.checked;
                        if (self.checked) {
                            root.item-checked(item);
                        } else {
                            root.item-unchecked(item);
                        }
                    }
                }
            }
        }

        in property <[[StandardListViewItem]]> table_row_data: [
            [
                { text: "Item 1.1" },
                { text: "" },
                { text: "" },
                { text: "Item 1.4" },
            ],
            [
                { text: "Item 2.1" },
                { text: "" },
                { text: "" },
                { text: "Item 2.4" },
            ],
        ];

        mainTable := StandardTableView {
            rows: table_row_data;
        }
    }
}
