import { SpinBox, Button, CheckBox, Slider, LineEdit, ScrollView, ListView,
    HorizontalBox, VerticalBox, GridBox, StandardButton, StandardTableView } from "std-widgets.slint";

import { ViewToDoItem } from "viewtodoitem.slint";

export component AppWindow inherits Window {
    preferred-width: 800px;
    preferred-height: 600px;
    min-width: 800px;
    min-height: 600px;

    callback item-checked(ViewToDoItem);
    callback item-unchecked(ViewToDoItem);

    in property <[ViewToDoItem]> todo-items: [
        { checked: false, title: "Item 1" },
        { checked: false, title: "Item 2" },
        { checked: false, title: "Item 3" },
    ];

    VerticalBox {
        ListView {
            for item in root.todo-items: HorizontalLayout {
                item-action := CheckBox {
                    text: item.title;
                    checked: item.checked;

                    toggled => {
                        item.checked = self.checked;
                        if (self.checked) {
                            root.item-checked(item);
                        } else {
                            root.item-unchecked(item);
                        }
                    }
                }
            }
        }
    }
}
