[package]
name = "todo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0"
rayon = "1.8.0"

[dependencies.uuid]
version = "1.4.1"
features = ["v4", "fast-rng", "macro-diagnostics", "serde"]
